name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run aifan:build
      - name: config1
        run: mkdir -p aifan/.vitepress/aifan/
      - name: config2
        run: mv aifan/.vitepress/dist/* aifan/.vitepress/aifan/
      - name: config3
        run: mv aifan/.vitepress/aifan aifan/.vitepress/dist/
      - name: config4
        run: mv aifan/.vitepress/dist/aifan/index.html aifan/.vitepress/dist/
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: aifan/.vitepress/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
